# fly.toml app configuration file generated for cascade-long-sun-2101 on 2025-12-31T13:15:07-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cascade-long-sun-2101'
primary_region = 'yyz'

[build]
  image = 'ghcr.io/tim-br/cascade:latest'

[env]
  AUTO_MIGRATE = 'true'
  CASCADE_NODE_ROLE = 'both'
  CASCADE_WORKERS = '4'
  DAGS_DIR = '/data/dags'
  DAGS_ENABLED = 'true'
  DAGS_SCAN_INTERVAL = '30'
  PHX_HOST = 'cascade.nauths.io'
  PORT = '4000'
  RELEASE_DISTRIBUTION = 'none'
  RELEASE_NODE = 'cascade'
  SQLITE_DATABASE_PATH = '/data/cascade.db'

[[mounts]]
  source = 'cascade_data'
  destination = '/data'
  initial_size = '1GB'

[http_service]
  internal_port = 4000
  force_https = false
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 500

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/'


[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
